name: Disable GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write

jobs:
  disable-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Disable GitHub Pages via GitHub API
        run: |
          curl -X DELETE \
          -H "Authorization: token ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pages
